CREATE SCHEMA IF NOT EXISTS `proyecto_final`;
USE `proyecto_final` ;

CREATE TABLE IF NOT EXISTS `cliente` (
  `id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `dni` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL
);


CREATE TABLE IF NOT EXISTS `venta` (
  `id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `fecha_alta` DATETIME(6) NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `cliente_id` BIGINT NULL DEFAULT NULL,
  CONSTRAINT fk_cliente_id foreign key(cliente_id) references cliente(id)
);

CREATE TABLE IF NOT EXISTS `producto` (
  `id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_alta` DATETIME(6) NULL DEFAULT NULL,
  `precio_compra` DOUBLE NULL DEFAULT NULL,
  `precio_venta` DOUBLE NULL DEFAULT NULL,
  `sku` VARCHAR(255) NULL DEFAULT NULL,
  `stock` INT NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `detalle_venta` (
  `id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL DEFAULT NULL,
  `subtotal` DOUBLE NULL DEFAULT NULL,
  `producto_id` BIGINT NULL DEFAULT NULL,
  `venta_id` BIGINT NULL DEFAULT NULL,
	CONSTRAINT fk_venta_id FOREIGN KEY(venta_id) REFERENCES venta(id),
    CONSTRAINT fk_producto_id FOREIGN KEY(producto_id) REFERENCES producto(id)
);

